name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: latest
          cache: true

      - name: Check formatting
        run: pixi run fmt
        if: matrix.os == 'ubuntu-latest'

      - name: Run clippy
        run: pixi run lint
        if: matrix.os == 'ubuntu-latest'

  build-test:
    name: Build test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-64
          - os: macos-latest  
            platform: osx-arm64
          - os: windows-latest
            platform: win-64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: latest
          cache: true

      - name: Build package
        shell: bash
        run: |
          pixi run test